image: node

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - mkdir public
    - mv dist/ public/
    - mv plugin/ public/
    - mv css/ public/
    - mv img/ public/
    - mv videos/ public/
    - mv index.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
