pages:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y git  # Install Git
    - git submodule update --init --recursive  # Clone the submodule repository
    - apt-get install -y make doxygen # Install Doxygen
  script:
    - cd ./doc/doxygen-awesome-css
    - git checkout v2.3.1
    - cd ../..
    - make create_doc  # Generate the documentation using your make command
    - mv ./doc/html/ public
  artifacts:
    paths:
      - public
  only:
    - main

