image: python:3.10-alpine

stages:
  - deploy

pages:
  # tags:
  #   - sphinx
  stage: deploy
  script:
    - cd ./docs/
    - python3 -m pip install sphinx sphinx_rtd_theme sphinx-tabs myst_parser
    - sphinx-build /src/ ../public/
  artifacts:
    paths:
      - public
  only:
    - main
