# Use the official Node.js image as the base image
FROM node:20-slim
# Set the working directory inside the Docker image
WORKDIR usr/src/app
# Copy package.json and package-lock.json to the working directory
COPY ../demos/node_js/package*.json ./
# Install project dependencies
RUN npm install
