# Use the official Node.js image as the base image
FROM node:20-slim
ARG UID=1000
ARG GID=1000

ARG MYUSER=container_user

WORKDIR /usr/src/app

RUN groupadd -g "${GID}" ${MYUSER} \
  && useradd --create-home --no-log-init -u "${UID}" -g "${GID}" ${MYUSER} \
  && chown ${MYUSER}:${MYUSER} -R /usr/src/app


USER $MYUSER

# Copy package.json and package-lock.json to the working directory
COPY --chown=$MYUSER$MYUSER ../demos/node_js/package*.json ./
# Install project dependencies
RUN npm install

