version: "3"
services:
  # Fix Ownership of Build Directory
  # Thanks to Bug in Docker itself
  # We need to use steps like this
  # Because by default, the volume directory
  # Is owned by Root
  # So this helps correct it
  change-vol-ownership:
    container_name: vol_ownership
    # We can use any image we want as long as we can chown
    image: ubuntu
    # Need a user priviliged enough to chown
    user: "root"
    env_file:
      - ".env"
    # Specify the group in question
    group_add:
      - "${GID:-1000}"
    volumes:
      - code_directory:/usr/src/app/:rw
      # The volume to chown
      #- disk:/usr/src/app/Data_these:rw
    command: chown -R ${GID:-1000}:${UID:-1000} /usr/src/app/

  my_base_service:
    container_name: base_service
    user: "${GID:-1000}:${UID:-1000}"
    working_dir: /usr/src/app
    build:
      context: .
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
        - "MYUSER=${MYUSER:-container_user}"
    env_file:
      - ".env"
    network_mode: host
    depends_on:
      change-vol-ownership:
        # Wait for the ownership to change
        condition: service_completed_successfully

  my_nvim:
    container_name: nvim_pg
    working_dir: /usr/src/app/
    build:
      context: .
      dockerfile: Dockerfile.editor
    env_file:
      - ".env"
    volumes:
      - code_directory:/usr/src/app/:rw
    command: nvim
    tty: true

  julia:
    extends:
      service: my_base_service
    container_name: julia-1-9-3_morph
    build:
      dockerfile: Dockerfile.julia
    extra_hosts:
      - "python-3-10:127.0.0.1"
    environment:
      - CONFIG_FILE_PATH=configs/dashboard_config_disk.json
    volumes:
      - code_directory:/usr/src/app/:rw
      - disk:/usr/src/app/Data_these:rw

    command: julia Dashboard_App.jl

  python:
    extends:
      service: my_base_service
    build:
      dockerfile: Dockerfile.python
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - code_directory:/usr/src/app/:rw
    command: python3 demos/python/main.py
    privileged: true # To avoid libGL errors

  latex:
    extends:
      service: my_base_service
    container_name: latex
    build:
      dockerfile: Dockerfile.latex
    volumes:
      - code_directory:/usr/src/app/:rw
    tty: true # makes the container running even when the command is finished.

  node_js:
    image: slides_js
    extends:
      service: my_base_service
    container_name: node_js
    build:
      context: .. # to add demos in build context
      dockerfile: ./install/Dockerfile.nodejs
    volumes:
      - code_directory:/usr/src/app/:rw
      - /usr/src/app/node_modules
    command: npm start
    network_mode: bridge
    ports:
      - 7346:7346
      - 35729:35729

volumes:
  disk:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DISK_DEVICE}
  code_directory:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CODE_DIRECTORY_DEVICE}
