# Use the official Node.js image as the base image
FROM node:20-alpine as base

WORKDIR /usr/src/app
# Copy package.json and package-lock.json to the working directory
COPY ../demos/node_js/package*.json ./


FROM base as dev
# Install project dependencies
RUN npm install


