#!/usr/bin/env bash

git clone --bare https://gitlab.com/pgalmiche/repo-setter.git $PWD/.repo_setter

# define config alias locally since the dotfiles
# aren't installed on the system yet

function repo_setter {
   git --git-dir=$PWD/.repo_setter --work-tree=$PWD $@
}

# create a directory to backup existing dotfiles to
mkdir -p .repo_setter-backup
repo_setter checkout
if [ $? = 0 ]; then
  echo "Checked out files from https://gitlab.com/pgalmiche/repo-setter.git";
  else
    echo "Moving existing files to ./.repo_setter-backup";
    repo_setter checkout 2>&1 | egrep "^\s+" | awk {'print $1'} | xargs -I{} sh -c 'mkdir -p .repo_setter-backup/$(dirname {}); mv {} .repo_setter-backup/{}'
fi

# checkout dotfiles from repo
repo_setter checkout

# remove the repo setter once used
echo ".repo_setter folder removed."
echo "You can find in the .repo_setter-backup folder your old files"
rm -r ./.repo_setter

rm README.md LICENCE
mv README.md.template README.md

# overwrite the [USER] etc in README.md
echo "Enter your git username:"
read -s USER </dev/tty
echo "Hello, $USER!"
sed -i 's/[USER]/$USER/g' README.md

echo "Enter your git repo name:"
read -s REPO </dev/tty
echo "Git repo: $REPO!"
sed -i 's/[YOUR_REPO]/$REPO/g' README.md
